export const state = {
  user: null,
  campaigns: [],
  campaign: null,
  membership: null,
  members: [],
  room: null,
  roomMessages: new Map(),
  roomEvents: null,
  roomEventCursor: 0,
  panel: null,
  packs: [],
  artifacts: [],
  artifact: null,
  releases: [],
  identities: [],
  assignments: [],
  studioArtifact: null,
  modules: [],
  module: null,
  moduleRuns: [],
  moduleEvents: null,
  characterCards: new Map(),
  characterDenied: new Set(),
  inspectedActorId: null,
  actingActorId: null,
  characterPage: "character",
  characterCollapsed: false,
  gridExpanded: false,
  roomMode: "table",
  selectedTargetId: null,
  gridDestination: null,
  animatedResolutions: new Set(),
  hydratingRoom: false,
};
