"""add community artifacts and identities

Revision ID: 2d87c3d3ec08
Revises: dbb86b934073
Create Date: 2026-08-13 02:22:28.250380
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "2d87c3d3ec08"
down_revision: Union[str, None] = "dbb86b934073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("artifact_type", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("system_id", sa.String(length=32), nullable=False),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("license_code", sa.String(length=64), nullable=False),
        sa.Column("rights_attested", sa.Boolean(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("forked_from_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("discussion_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["forked_from_artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "slug", name="uq_artifact_owner_slug"),
    )
    op.create_index(
        "ix_artifact_catalog", "artifacts", ["visibility", "status", "artifact_type"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_forked_from_artifact_id"),
        "artifacts",
        ["forked_from_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifacts_owner_user_id"), "artifacts", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_artifacts_status"), "artifacts", ["status"], unique=False)
    op.create_index(op.f("ix_artifacts_system_id"), "artifacts", ["system_id"], unique=False)
    op.create_index(op.f("ix_artifacts_title"), "artifacts", ["title"], unique=False)
    op.create_index(op.f("ix_artifacts_visibility"), "artifacts", ["visibility"], unique=False)
    op.create_table(
        "community_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reporter_user_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=24), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("details", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("resolution", sa.String(length=2000), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reporter_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_community_report_queue", "community_reports", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_community_reports_reporter_user_id"),
        "community_reports",
        ["reporter_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_reports_status"), "community_reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_community_reports_target_id"), "community_reports", ["target_id"], unique=False
    )
    op.create_table(
        "artifact_collaborators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "user_id", name="uq_artifact_collaborator"),
    )
    op.create_index(
        op.f("ix_artifact_collaborators_artifact_id"),
        "artifact_collaborators",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_collaborators_user_id"),
        "artifact_collaborators",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "artifact_favorites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "user_id", name="uq_artifact_favorite"),
    )
    op.create_index(
        op.f("ix_artifact_favorites_artifact_id"),
        "artifact_favorites",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_favorites_user_id"), "artifact_favorites", ["user_id"], unique=False
    )
    op.create_table(
        "artifact_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("changelog", sa.String(length=4000), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("compatibility", sa.JSON(), nullable=False),
        sa.Column("private_pack_id", sa.String(length=36), nullable=True),
        sa.Column("contains_private_source", sa.Boolean(), nullable=False),
        sa.Column("agent_review", sa.JSON(), nullable=False),
        sa.Column("agent_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("moderated_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("moderation_notes", sa.String(length=2000), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["moderated_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["private_pack_id"], ["private_packs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "version", name="uq_artifact_release_version"),
    )
    op.create_index(
        "ix_artifact_release_catalog", "artifact_releases", ["status", "published_at"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_releases_artifact_id"), "artifact_releases", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_releases_private_pack_id"),
        "artifact_releases",
        ["private_pack_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_releases_status"), "artifact_releases", ["status"], unique=False
    )
    op.create_table(
        "agent_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("handle", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("identity_kind", sa.String(length=24), nullable=False),
        sa.Column("system_id", sa.String(length=32), nullable=False),
        sa.Column("bio", sa.String(length=2000), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("availability", sa.String(length=24), nullable=False),
        sa.Column("active_soul_release_id", sa.String(length=36), nullable=False),
        sa.Column("memory_policy", sa.JSON(), nullable=False),
        sa.Column("public_profile", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_soul_release_id"], ["artifact_releases.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("handle", name="uq_agent_identity_handle"),
    )
    op.create_index(
        op.f("ix_agent_identities_active_soul_release_id"),
        "agent_identities",
        ["active_soul_release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_identities_identity_kind"),
        "agent_identities",
        ["identity_kind"],
        unique=False,
    )
    op.create_index(op.f("ix_agent_identities_name"), "agent_identities", ["name"], unique=False)
    op.create_index(
        op.f("ix_agent_identities_owner_user_id"),
        "agent_identities",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_identities_status"), "agent_identities", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_identities_system_id"), "agent_identities", ["system_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_identities_visibility"), "agent_identities", ["visibility"], unique=False
    )
    op.create_index(
        "ix_agent_identity_catalog",
        "agent_identities",
        ["visibility", "status", "identity_kind"],
        unique=False,
    )
    op.create_table(
        "artifact_installations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("installed_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=True),
        sa.Column("target_key", sa.String(length=100), nullable=False),
        sa.Column("install_kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("runtime_ref", sa.String(length=160), nullable=True),
        sa.Column("campaign_pack_projection_id", sa.String(length=36), nullable=True),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign_projections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["campaign_pack_projection_id"], ["campaign_pack_projections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["installed_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["release_id"], ["artifact_releases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "installed_by_user_id",
            "release_id",
            "target_key",
            name="uq_artifact_install_target",
        ),
    )
    op.create_index(
        "ix_artifact_install_owner",
        "artifact_installations",
        ["installed_by_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_installations_artifact_id"),
        "artifact_installations",
        ["artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_installations_campaign_id"),
        "artifact_installations",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_installations_installed_by_user_id"),
        "artifact_installations",
        ["installed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_installations_release_id"),
        "artifact_installations",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_installations_status"), "artifact_installations", ["status"], unique=False
    )
    op.create_table(
        "community_posts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("author_user_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=24), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("audience", sa.String(length=24), nullable=False),
        sa.Column("spoiler", sa.Boolean(), nullable=False),
        sa.Column("body", sa.String(length=10000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["community_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["release_id"], ["artifact_releases.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_community_post_target",
        "community_posts",
        ["target_type", "target_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_posts_author_user_id"),
        "community_posts",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_community_posts_parent_id"), "community_posts", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_community_posts_release_id"), "community_posts", ["release_id"], unique=False
    )
    op.create_index(op.f("ix_community_posts_status"), "community_posts", ["status"], unique=False)
    op.create_table(
        "identity_campaign_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identity_id", sa.String(length=36), nullable=False),
        sa.Column("active_key", sa.String(length=140), nullable=True),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("soul_release_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("invited_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("quota_payer_user_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("memory_namespace", sa.String(length=200), nullable=False),
        sa.Column("mcp_receipt", sa.JSON(), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign_projections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["identity_id"], ["agent_identities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quota_payer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["soul_release_id"], ["artifact_releases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "invited_by_user_id", "idempotency_key", name="uq_identity_invite_retry"
        ),
    )
    op.create_index(
        op.f("ix_identity_campaign_assignments_active_key"),
        "identity_campaign_assignments",
        ["active_key"],
        unique=True,
    )
    op.create_index(
        "ix_identity_assignment_active",
        "identity_campaign_assignments",
        ["campaign_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_campaign_assignments_campaign_id"),
        "identity_campaign_assignments",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_campaign_assignments_identity_id"),
        "identity_campaign_assignments",
        ["identity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_campaign_assignments_invited_by_user_id"),
        "identity_campaign_assignments",
        ["invited_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_campaign_assignments_status"),
        "identity_campaign_assignments",
        ["status"],
        unique=False,
    )
    op.create_table(
        "identity_memory_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("memory_key", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["identity_campaign_assignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "memory_key", name="uq_identity_memory_key"),
    )
    op.create_index(
        op.f("ix_identity_memory_entries_assignment_id"),
        "identity_memory_entries",
        ["assignment_id"],
        unique=False,
    )
    with op.batch_alter_table("agent_conversations") as batch_op:
        batch_op.add_column(
            sa.Column("identity_assignment_id", sa.String(length=36), nullable=True)
        )
        batch_op.create_index(
            "ix_agent_conversations_identity_assignment_id",
            ["identity_assignment_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_agent_conversation_identity_assignment",
            "identity_campaign_assignments",
            ["identity_assignment_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_conversations") as batch_op:
        batch_op.drop_constraint("fk_agent_conversation_identity_assignment", type_="foreignkey")
        batch_op.drop_index("ix_agent_conversations_identity_assignment_id")
        batch_op.drop_column("identity_assignment_id")
    op.drop_index(
        op.f("ix_identity_campaign_assignments_active_key"),
        table_name="identity_campaign_assignments",
    )
    op.drop_index(
        op.f("ix_identity_memory_entries_assignment_id"), table_name="identity_memory_entries"
    )
    op.drop_table("identity_memory_entries")
    op.drop_index(
        op.f("ix_identity_campaign_assignments_status"), table_name="identity_campaign_assignments"
    )
    op.drop_index(
        op.f("ix_identity_campaign_assignments_invited_by_user_id"),
        table_name="identity_campaign_assignments",
    )
    op.drop_index(
        op.f("ix_identity_campaign_assignments_identity_id"),
        table_name="identity_campaign_assignments",
    )
    op.drop_index(
        op.f("ix_identity_campaign_assignments_campaign_id"),
        table_name="identity_campaign_assignments",
    )
    op.drop_index("ix_identity_assignment_active", table_name="identity_campaign_assignments")
    op.drop_table("identity_campaign_assignments")
    op.drop_index(op.f("ix_community_posts_status"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_release_id"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_parent_id"), table_name="community_posts")
    op.drop_index(op.f("ix_community_posts_author_user_id"), table_name="community_posts")
    op.drop_index("ix_community_post_target", table_name="community_posts")
    op.drop_table("community_posts")
    op.drop_index(op.f("ix_artifact_installations_status"), table_name="artifact_installations")
    op.drop_index(op.f("ix_artifact_installations_release_id"), table_name="artifact_installations")
    op.drop_index(
        op.f("ix_artifact_installations_installed_by_user_id"), table_name="artifact_installations"
    )
    op.drop_index(
        op.f("ix_artifact_installations_campaign_id"), table_name="artifact_installations"
    )
    op.drop_index(
        op.f("ix_artifact_installations_artifact_id"), table_name="artifact_installations"
    )
    op.drop_index("ix_artifact_install_owner", table_name="artifact_installations")
    op.drop_table("artifact_installations")
    op.drop_index("ix_agent_identity_catalog", table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_visibility"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_system_id"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_status"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_owner_user_id"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_name"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_identity_kind"), table_name="agent_identities")
    op.drop_index(op.f("ix_agent_identities_active_soul_release_id"), table_name="agent_identities")
    op.drop_table("agent_identities")
    op.drop_index(op.f("ix_artifact_releases_status"), table_name="artifact_releases")
    op.drop_index(op.f("ix_artifact_releases_private_pack_id"), table_name="artifact_releases")
    op.drop_index(op.f("ix_artifact_releases_artifact_id"), table_name="artifact_releases")
    op.drop_index("ix_artifact_release_catalog", table_name="artifact_releases")
    op.drop_table("artifact_releases")
    op.drop_index(op.f("ix_artifact_favorites_user_id"), table_name="artifact_favorites")
    op.drop_index(op.f("ix_artifact_favorites_artifact_id"), table_name="artifact_favorites")
    op.drop_table("artifact_favorites")
    op.drop_index(op.f("ix_artifact_collaborators_user_id"), table_name="artifact_collaborators")
    op.drop_index(
        op.f("ix_artifact_collaborators_artifact_id"), table_name="artifact_collaborators"
    )
    op.drop_table("artifact_collaborators")
    op.drop_index(op.f("ix_community_reports_target_id"), table_name="community_reports")
    op.drop_index(op.f("ix_community_reports_status"), table_name="community_reports")
    op.drop_index(op.f("ix_community_reports_reporter_user_id"), table_name="community_reports")
    op.drop_index("ix_community_report_queue", table_name="community_reports")
    op.drop_table("community_reports")
    op.drop_index(op.f("ix_artifacts_visibility"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_title"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_system_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_status"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_owner_user_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_forked_from_artifact_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_index("ix_artifact_catalog", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
