"""add module studio m1 m4

Revision ID: c5f887f6f8ac
Revises: 2d87c3d3ec08
Create Date: 2026-08-13 04:29:00.430092
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c5f887f6f8ac"
down_revision: Union[str, None] = "2d87c3d3ec08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_notification_inbox",
        "user_notifications",
        ["user_id", "read_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notifications_notification_type"),
        "user_notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_notifications_read_at"), "user_notifications", ["read_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_notifications_user_id"), "user_notifications", ["user_id"], unique=False
    )
    op.create_table(
        "module_projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("authoring_campaign_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("system_id", sa.String(length=32), nullable=False),
        sa.Column("edition", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("specification", sa.JSON(), nullable=False),
        sa.Column("outline", sa.JSON(), nullable=False),
        sa.Column("outline_revision", sa.Integer(), nullable=False),
        sa.Column("current_source_id", sa.String(length=36), nullable=True),
        sa.Column("mcp_job_id", sa.String(length=64), nullable=True),
        sa.Column("mcp_module_id", sa.String(length=160), nullable=True),
        sa.Column("mcp_draft_revision", sa.Integer(), nullable=True),
        sa.Column("mcp_draft_state", sa.String(length=32), nullable=True),
        sa.Column("inspection", sa.JSON(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.Column("review", sa.JSON(), nullable=False),
        sa.Column("package_decisions", sa.JSON(), nullable=False),
        sa.Column("final_artifact", sa.String(length=500), nullable=True),
        sa.Column("final_pack_id", sa.String(length=160), nullable=True),
        sa.Column("final_checksum", sa.String(length=64), nullable=True),
        sa.Column("finalization", sa.JSON(), nullable=False),
        sa.Column("published_release_id", sa.String(length=36), nullable=True),
        sa.Column("budget_tokens", sa.Integer(), nullable=False),
        sa.Column("used_tokens", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("last_error", sa.String(length=2000), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authoring_campaign_id"], ["campaign_projections.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "slug", name="uq_module_project_owner_slug"),
    )
    op.create_index(
        "ix_module_project_owner_status",
        "module_projects",
        ["owner_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_projects_authoring_campaign_id"),
        "module_projects",
        ["authoring_campaign_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_module_projects_current_source_id"),
        "module_projects",
        ["current_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_projects_final_checksum"),
        "module_projects",
        ["final_checksum"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_projects_final_pack_id"), "module_projects", ["final_pack_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_projects_mcp_job_id"), "module_projects", ["mcp_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_projects_owner_user_id"), "module_projects", ["owner_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_projects_published_release_id"),
        "module_projects",
        ["published_release_id"],
        unique=False,
    )
    op.create_index(op.f("ix_module_projects_status"), "module_projects", ["status"], unique=False)
    op.create_table(
        "module_installations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("installed_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("runtime_module_id", sa.String(length=160), nullable=True),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign_projections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["installed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["module_projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "version", "campaign_id", name="uq_module_project_install_target"
        ),
    )
    op.create_index(
        op.f("ix_module_installations_campaign_id"),
        "module_installations",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_installations_project_id"),
        "module_installations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_installations_status"), "module_installations", ["status"], unique=False
    )
    op.create_table(
        "module_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reservation_id", sa.String(length=36), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("upstream_request_id", sa.String(length=100), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["module_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reservation_id"], ["quota_reservations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requested_by_user_id", "idempotency_key", name="uq_module_run_retry"),
    )
    op.create_index(
        "ix_module_run_project", "module_runs", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_module_run_queue", "module_runs", ["status", "available_at", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_module_runs_lease_expires_at"), "module_runs", ["lease_expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_module_runs_lease_owner"), "module_runs", ["lease_owner"], unique=False
    )
    op.create_index(op.f("ix_module_runs_project_id"), "module_runs", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_module_runs_requested_by_user_id"),
        "module_runs",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_module_runs_run_type"), "module_runs", ["run_type"], unique=False)
    op.create_index(op.f("ix_module_runs_status"), "module_runs", ["status"], unique=False)
    op.create_table(
        "module_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("rights_basis", sa.String(length=32), nullable=False),
        sa.Column("license_code", sa.String(length=64), nullable=False),
        sa.Column("attribution", sa.String(length=2000), nullable=False),
        sa.Column("public_eligible", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["module_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "generation", name="uq_module_source_generation"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "ix_module_source_project_status", "module_sources", ["project_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_module_sources_project_id"), "module_sources", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_module_sources_sha256"), "module_sources", ["sha256"], unique=False)
    op.create_index(op.f("ix_module_sources_status"), "module_sources", ["status"], unique=False)
    op.create_table(
        "module_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("decision_type", sa.String(length=40), nullable=False),
        sa.Column("project_revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["module_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["module_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_module_decision_project", "module_decisions", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_module_decisions_decision_type"),
        "module_decisions",
        ["decision_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_module_decisions_project_id"), "module_decisions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_decisions_run_id"), "module_decisions", ["run_id"], unique=False
    )
    with op.batch_alter_table("artifact_releases") as batch_op:
        batch_op.add_column(sa.Column("module_project_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("content_artifact", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("content_checksum", sa.String(length=64), nullable=True))
        batch_op.create_index("ix_artifact_releases_content_checksum", ["content_checksum"])
        batch_op.create_index("ix_artifact_releases_module_project_id", ["module_project_id"])
        batch_op.create_foreign_key(
            "fk_artifact_release_module_project",
            "module_projects",
            ["module_project_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    with op.batch_alter_table("campaign_projections") as batch_op:
        batch_op.add_column(
            sa.Column(
                "purpose",
                sa.String(length=24),
                nullable=False,
                server_default="play",
            )
        )
        batch_op.create_index("ix_campaign_projections_purpose", ["purpose"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign_projections") as batch_op:
        batch_op.drop_index("ix_campaign_projections_purpose")
        batch_op.drop_column("purpose")
    with op.batch_alter_table("artifact_releases") as batch_op:
        batch_op.drop_constraint("fk_artifact_release_module_project", type_="foreignkey")
        batch_op.drop_index("ix_artifact_releases_module_project_id")
        batch_op.drop_index("ix_artifact_releases_content_checksum")
        batch_op.drop_column("content_checksum")
        batch_op.drop_column("content_artifact")
        batch_op.drop_column("module_project_id")
    op.drop_index(op.f("ix_module_decisions_run_id"), table_name="module_decisions")
    op.drop_index(op.f("ix_module_decisions_project_id"), table_name="module_decisions")
    op.drop_index(op.f("ix_module_decisions_decision_type"), table_name="module_decisions")
    op.drop_index("ix_module_decision_project", table_name="module_decisions")
    op.drop_table("module_decisions")
    op.drop_index(op.f("ix_module_sources_status"), table_name="module_sources")
    op.drop_index(op.f("ix_module_sources_sha256"), table_name="module_sources")
    op.drop_index(op.f("ix_module_sources_project_id"), table_name="module_sources")
    op.drop_index("ix_module_source_project_status", table_name="module_sources")
    op.drop_table("module_sources")
    op.drop_index(op.f("ix_module_runs_status"), table_name="module_runs")
    op.drop_index(op.f("ix_module_runs_run_type"), table_name="module_runs")
    op.drop_index(op.f("ix_module_runs_requested_by_user_id"), table_name="module_runs")
    op.drop_index(op.f("ix_module_runs_project_id"), table_name="module_runs")
    op.drop_index(op.f("ix_module_runs_lease_owner"), table_name="module_runs")
    op.drop_index(op.f("ix_module_runs_lease_expires_at"), table_name="module_runs")
    op.drop_index("ix_module_run_queue", table_name="module_runs")
    op.drop_index("ix_module_run_project", table_name="module_runs")
    op.drop_table("module_runs")
    op.drop_index(op.f("ix_module_installations_status"), table_name="module_installations")
    op.drop_index(op.f("ix_module_installations_project_id"), table_name="module_installations")
    op.drop_index(op.f("ix_module_installations_campaign_id"), table_name="module_installations")
    op.drop_table("module_installations")
    op.drop_index(op.f("ix_module_projects_status"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_published_release_id"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_owner_user_id"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_mcp_job_id"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_final_pack_id"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_final_checksum"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_current_source_id"), table_name="module_projects")
    op.drop_index(op.f("ix_module_projects_authoring_campaign_id"), table_name="module_projects")
    op.drop_index("ix_module_project_owner_status", table_name="module_projects")
    op.drop_table("module_projects")
    op.drop_index(op.f("ix_user_notifications_user_id"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_read_at"), table_name="user_notifications")
    op.drop_index(op.f("ix_user_notifications_notification_type"), table_name="user_notifications")
    op.drop_index("ix_user_notification_inbox", table_name="user_notifications")
    op.drop_table("user_notifications")
    # ### end Alembic commands ###
