"""initial_schema

Revision ID: dbb86b934073
Revises:
Create Date: 2026-08-12 23:45:24.714553
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'dbb86b934073'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_subject', 'audit_events', ['subject_type', 'subject_id', 'created_at'], unique=False)
    op.create_table('campaign_projections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('mcp_revision', sa.Integer(), nullable=False),
    sa.Column('mcp_receipt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_projections_owner_user_id'), 'campaign_projections', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_campaign_projections_status'), 'campaign_projections', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_projections_visibility'), 'campaign_projections', ['visibility'], unique=False)
    op.create_table('private_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rights_attested', sa.Boolean(), nullable=False),
    sa.Column('distribution', sa.String(length=24), nullable=False),
    sa.Column('review_notes', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'pack_id', 'version', name='uq_private_pack_version'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_private_packs_kind'), 'private_packs', ['kind'], unique=False)
    op.create_index(op.f('ix_private_packs_owner_user_id'), 'private_packs', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_private_packs_pack_id'), 'private_packs', ['pack_id'], unique=False)
    op.create_index(op.f('ix_private_packs_sha256'), 'private_packs', ['sha256'], unique=False)
    op.create_index(op.f('ix_private_packs_status'), 'private_packs', ['status'], unique=False)
    op.create_table('quota_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quota_grant_lookup', 'quota_grants', ['user_id', 'metric', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_quota_grants_user_id'), 'quota_grants', ['user_id'], unique=False)
    op.create_table('quota_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('settled_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_quota_reservation_retry')
    )
    op.create_index(op.f('ix_quota_reservations_campaign_id'), 'quota_reservations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_quota_reservations_expires_at'), 'quota_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_quota_reservations_metric'), 'quota_reservations', ['metric'], unique=False)
    op.create_index(op.f('ix_quota_reservations_status'), 'quota_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_quota_reservations_user_id'), 'quota_reservations', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'status', name='uq_active_user_subscription')
    )
    op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('actor_binding_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('can_control', sa.Boolean(), nullable=False),
    sa.Column('can_view_private', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mcp_receipt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'actor_id', 'user_id', name='uq_actor_user_binding')
    )
    op.create_index(op.f('ix_actor_binding_projections_actor_id'), 'actor_binding_projections', ['actor_id'], unique=False)
    op.create_index(op.f('ix_actor_binding_projections_campaign_id'), 'actor_binding_projections', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_actor_binding_projections_user_id'), 'actor_binding_projections', ['user_id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_campaign_id'), 'agent_conversations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_status'), 'agent_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_table('campaign_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('intended_role', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_invites_campaign_id'), 'campaign_invites', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_invites_expires_at'), 'campaign_invites', ['expires_at'], unique=False)
    op.create_index(op.f('ix_campaign_invites_token_hash'), 'campaign_invites', ['token_hash'], unique=True)
    op.create_table('campaign_membership_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mcp_receipt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_member')
    )
    op.create_index(op.f('ix_campaign_membership_projections_campaign_id'), 'campaign_membership_projections', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_membership_projections_role'), 'campaign_membership_projections', ['role'], unique=False)
    op.create_index(op.f('ix_campaign_membership_projections_status'), 'campaign_membership_projections', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_membership_projections_user_id'), 'campaign_membership_projections', ['user_id'], unique=False)
    op.create_table('campaign_pack_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('private_pack_id', sa.String(length=36), nullable=False),
    sa.Column('imported_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('runtime_ref', sa.String(length=160), nullable=True),
    sa.Column('mcp_receipt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['private_pack_id'], ['private_packs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'private_pack_id', name='uq_campaign_private_pack')
    )
    op.create_index(op.f('ix_campaign_pack_projections_campaign_id'), 'campaign_pack_projections', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_pack_projections_private_pack_id'), 'campaign_pack_projections', ['private_pack_id'], unique=False)
    op.create_index(op.f('ix_campaign_pack_projections_status'), 'campaign_pack_projections', ['status'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('applicant_user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_role', sa.String(length=24), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mcp_receipt', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_projections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_join_request_pending', 'join_requests', ['campaign_id', 'applicant_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_join_requests_applicant_user_id'), 'join_requests', ['applicant_user_id'], unique=False)
    op.create_index(op.f('ix_join_requests_campaign_id'), 'join_requests', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_join_requests_status'), 'join_requests', ['status'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['quota_reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_usage_retry')
    )
    op.create_index(op.f('ix_usage_ledger_campaign_id'), 'usage_ledger', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_request_id'), 'usage_ledger', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_user_id'), 'usage_ledger', ['user_id'], unique=False)
    op.create_index('ix_usage_period', 'usage_ledger', ['user_id', 'metric', 'occurred_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('user_content', sa.Text(), nullable=False),
    sa.Column('assistant_content', sa.Text(), nullable=True),
    sa.Column('upstream_request_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_agent_run_retry')
    )
    op.create_index('ix_agent_run_conversation', 'agent_runs', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_campaign_id'), 'agent_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_campaign_id'), table_name='agent_runs')
    op.drop_index('ix_agent_run_conversation', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_usage_period', table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_user_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_request_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_campaign_id'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_join_requests_status'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_campaign_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_applicant_user_id'), table_name='join_requests')
    op.drop_index('ix_join_request_pending', table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_campaign_pack_projections_status'), table_name='campaign_pack_projections')
    op.drop_index(op.f('ix_campaign_pack_projections_private_pack_id'), table_name='campaign_pack_projections')
    op.drop_index(op.f('ix_campaign_pack_projections_campaign_id'), table_name='campaign_pack_projections')
    op.drop_table('campaign_pack_projections')
    op.drop_index(op.f('ix_campaign_membership_projections_user_id'), table_name='campaign_membership_projections')
    op.drop_index(op.f('ix_campaign_membership_projections_status'), table_name='campaign_membership_projections')
    op.drop_index(op.f('ix_campaign_membership_projections_role'), table_name='campaign_membership_projections')
    op.drop_index(op.f('ix_campaign_membership_projections_campaign_id'), table_name='campaign_membership_projections')
    op.drop_table('campaign_membership_projections')
    op.drop_index(op.f('ix_campaign_invites_token_hash'), table_name='campaign_invites')
    op.drop_index(op.f('ix_campaign_invites_expires_at'), table_name='campaign_invites')
    op.drop_index(op.f('ix_campaign_invites_campaign_id'), table_name='campaign_invites')
    op.drop_table('campaign_invites')
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_status'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_campaign_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_actor_binding_projections_user_id'), table_name='actor_binding_projections')
    op.drop_index(op.f('ix_actor_binding_projections_campaign_id'), table_name='actor_binding_projections')
    op.drop_index(op.f('ix_actor_binding_projections_actor_id'), table_name='actor_binding_projections')
    op.drop_table('actor_binding_projections')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_quota_reservations_user_id'), table_name='quota_reservations')
    op.drop_index(op.f('ix_quota_reservations_status'), table_name='quota_reservations')
    op.drop_index(op.f('ix_quota_reservations_metric'), table_name='quota_reservations')
    op.drop_index(op.f('ix_quota_reservations_expires_at'), table_name='quota_reservations')
    op.drop_index(op.f('ix_quota_reservations_campaign_id'), table_name='quota_reservations')
    op.drop_table('quota_reservations')
    op.drop_index(op.f('ix_quota_grants_user_id'), table_name='quota_grants')
    op.drop_index('ix_quota_grant_lookup', table_name='quota_grants')
    op.drop_table('quota_grants')
    op.drop_index(op.f('ix_private_packs_status'), table_name='private_packs')
    op.drop_index(op.f('ix_private_packs_sha256'), table_name='private_packs')
    op.drop_index(op.f('ix_private_packs_pack_id'), table_name='private_packs')
    op.drop_index(op.f('ix_private_packs_owner_user_id'), table_name='private_packs')
    op.drop_index(op.f('ix_private_packs_kind'), table_name='private_packs')
    op.drop_table('private_packs')
    op.drop_index(op.f('ix_campaign_projections_visibility'), table_name='campaign_projections')
    op.drop_index(op.f('ix_campaign_projections_status'), table_name='campaign_projections')
    op.drop_index(op.f('ix_campaign_projections_owner_user_id'), table_name='campaign_projections')
    op.drop_table('campaign_projections')
    op.drop_index('ix_audit_subject', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index('ix_outbox_pending', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
