const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={user:null,campaigns:[],campaign:null,membership:null,members:[],conversation:null,packs:[]};
async function api(path,options={}){const method=(options.method||"GET").toUpperCase(),headers={...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})};const r=await fetch(path,{...options,method,headers,credentials:"same-origin"});if(r.status===204)return null;const body=await r.json().catch(()=>({detail:`HTTP ${r.status}`}));if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);return body}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function text(tag,value,klass=""){const el=document.createElement(tag);el.textContent=value;if(klass)el.className=klass;return el}
function button(label,handler,klass=""){const el=text("button",label,klass);el.type="button";el.onclick=handler;return el}
async function boot(){try{state.user=(await api("/api/auth/me")).user;showApp()}catch{$("#auth").hidden=false}}
function showApp(){$("#auth").hidden=true;$("#app").hidden=false;$("#identity").textContent=state.user.display_name;loadCampaigns();loadUsage()}
$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$("#name-row").hidden=b.dataset.mode!=="register";$("#auth-form").dataset.mode=b.dataset.mode});
$("#auth-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),mode=e.target.dataset.mode||"login";try{const body={email:f.get("email"),password:f.get("password")};if(mode==="register")body.display_name=f.get("display_name");state.user=(await api(`/api/auth/${mode}`,{method:"POST",body:JSON.stringify(body)})).user;showApp()}catch(err){$("#auth-error").textContent=err.message}};
$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.reload()};
$$('.nav[data-view]').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.hidden=v.id!==`${b.dataset.view}-view`);if(b.dataset.view==='packs')loadPacks();if(b.dataset.view==='usage')loadUsage()});
async function loadCampaigns(){state.campaigns=await api("/api/campaigns");const list=$("#campaign-list");list.replaceChildren();for(const c of state.campaigns){const card=text("article","","card campaign");card.append(text("p",c.system_id.toUpperCase(),"eyebrow"),text("h3",c.name));const meta=text("div","","meta");meta.append(text("span",c.visibility),text("span",`rev ${c.mcp_revision}`));card.append(meta);card.onclick=()=>openCampaign(c);list.append(card)}}
$("#new-campaign").onclick=()=>$("#campaign-form").hidden=false;$('[data-close]').onclick=()=>$("#campaign-form").hidden=true;
$("#campaign-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api("/api/campaigns",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(Object.fromEntries(f))});e.target.hidden=true;e.target.reset();toast("战役已创建");loadCampaigns()};
$("#invite-accept-form").onsubmit=async e=>{e.preventDefault();const token=new FormData(e.target).get("token");try{const result=await api("/api/invites/accept",{method:"POST",body:JSON.stringify({token,message:""})});toast(result.status==="approved"?"已加入战役":"加入申请已提交");e.target.reset();loadCampaigns()}catch(err){toast(err.message)}};
async function refreshRuntime(){if(!state.campaign)return;const runtime=await api(`/api/campaigns/${state.campaign.id}/runtime`),authoritative=runtime.result||runtime;$("#room-phase").textContent=authoritative.effective_game_phase||"—"}
async function openCampaign(c){state.campaign=c;$("#campaign-list").hidden=true;$("#invite-accept-form").hidden=true;$("#new-campaign").hidden=true;$("#campaign-room").hidden=false;$("#room-title").textContent=c.name;await refreshRuntime();state.members=await api(`/api/campaigns/${c.id}/members`);state.membership=state.members.find(m=>m.user_id===state.user.id);renderMembers();const convs=await api(`/api/campaigns/${c.id}/agent/conversations`);state.conversation=convs[0]||await api(`/api/campaigns/${c.id}/agent/conversations`,{method:"POST",body:JSON.stringify({title:"战役会话"})});await loadRuns();await loadDmTools()}
function renderMembers(){const el=$("#members");el.replaceChildren();const canRemove=["owner","dm"].includes(state.membership?.role),isOwner=state.membership?.role==="owner";for(const m of state.members){const row=text("div","","review-row");row.append(text("span",`${m.display_name} · ${m.role}`));if(isOwner&&m.role!=="owner")row.append(button(m.role==="dm"?"设为玩家":"设为 DM",()=>changeMemberRole(m.user_id,m.role==="dm"?"player":"dm")));if(canRemove&&m.role!=="owner"&&m.user_id!==state.user.id)row.append(button("移除",()=>removeMember(m.user_id)));el.append(row)}const select=$("#actor-user");select.replaceChildren(...state.members.map(m=>{const o=text("option",`${m.display_name} · ${m.role}`);o.value=m.user_id;return o}))}
async function removeMember(userId){if(!confirm("撤销该成员及其全部 Actor 权限？此操作仅能在 Lobby 执行。"))return;try{await api(`/api/campaigns/${state.campaign.id}/members/${userId}`,{method:"DELETE"});toast("成员权限已由 D&D MCP 撤销");await openCampaign(state.campaign)}catch(err){toast(err.message)}}
async function changeMemberRole(userId,role){try{await api(`/api/campaigns/${state.campaign.id}/members/${userId}/role`,{method:"PATCH",body:JSON.stringify({role})});toast("战役角色已由 D&D MCP 更新");await openCampaign(state.campaign)}catch(err){toast(err.message)}}
async function loadRuns(){const runs=await api(`/api/campaigns/${state.campaign.id}/agent/conversations/${state.conversation.id}/runs`);$("#messages").replaceChildren();for(const run of runs){addBubble(run.user_content,"user");if(run.assistant_content)addBubble(run.assistant_content,"agent");else if(run.status==="failed")addBubble("此前请求失败，额度已释放。","agent")}}
async function loadDmTools(){const isDm=["owner","dm"].includes(state.membership?.role);$("#dm-tools").hidden=!isDm;if(!isDm)return;const requests=await api(`/api/campaigns/${state.campaign.id}/join-requests`),root=$("#join-requests");root.replaceChildren();for(const item of requests.filter(x=>x.status==="pending")){const row=text("div","","review-row");row.append(text("span",`${item.applicant_user_id} ${item.message||""}`),button("批准",()=>decideJoin(item.id,"approved"),"primary"),button("拒绝",()=>decideJoin(item.id,"rejected")));root.append(row)}await loadCampaignPacks()}
async function decideJoin(id,decision){await api(`/api/campaigns/${state.campaign.id}/join-requests/${id}/decision`,{method:"POST",body:JSON.stringify({decision})});toast(decision==="approved"?"申请已批准":"申请已拒绝");await openCampaign(state.campaign)}
$("#actor-binding-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),actorId=f.get("actor_id"),body={user_id:f.get("user_id"),can_control:f.has("can_control"),can_view_private:f.has("can_view_private")};try{await api(`/api/campaigns/${state.campaign.id}/actors/${encodeURIComponent(actorId)}/binding`,{method:"PUT",body:JSON.stringify(body)});toast("Actor 权限已由 MCP 确认")}catch(err){toast(err.message)}};
async function loadCampaignPacks(){state.packs=await api("/api/packs");const imported=await api(`/api/packs/campaigns/${state.campaign.id}`),byId=new Map(imported.map(x=>[x.private_pack_id,x])),owned=new Set(state.packs.map(x=>x.id)),root=$("#campaign-packs");root.replaceChildren();for(const pack of state.packs){const row=text("div","","review-row"),projection=byId.get(pack.id);row.append(text("span",`${pack.title} · ${pack.version}`));if(projection?.status==="activated"||pack.kind==="preset")row.append(text("span",projection?.status==="activated"?"已激活":"已导入角色库","phase"));else if(projection)row.append(button("激活",()=>activatePack(pack.id),"primary"));else row.append(button("导入",()=>importPack(pack.id)));root.append(row)}for(const projection of imported.filter(x=>!owned.has(x.private_pack_id))){const row=text("div","","review-row");row.append(text("span",`战役私有 Pack · ${projection.private_pack_id.slice(0,8)}`));if(projection.status==="activated")row.append(text("span","已激活","phase"));else row.append(button("激活",()=>activatePack(projection.private_pack_id),"primary"));root.append(row)}}
async function importPack(packId){try{await api(`/api/packs/${packId}/campaigns/${state.campaign.id}/import`,{method:"POST"});toast("Pack 已由 D&D MCP 导入");loadCampaignPacks()}catch(err){toast(err.message)}}
async function activatePack(packId){try{await api(`/api/packs/${packId}/campaigns/${state.campaign.id}/activate`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()}});toast("Pack 已由 D&D MCP 激活");loadCampaignPacks()}catch(err){toast(err.message)}}
$("#back-campaigns").onclick=()=>{$("#campaign-room").hidden=true;$("#campaign-list").hidden=false;$("#invite-accept-form").hidden=false;$("#new-campaign").hidden=false};
$("#message-form").onsubmit=async e=>{e.preventDefault();const field=e.target.elements.content,content=field.value.trim();if(!content)return;addBubble(content,"user");field.value="";try{const run=await api(`/api/campaigns/${state.campaign.id}/agent/conversations/${state.conversation.id}/messages`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({content})});addBubble(run.assistant_content,"agent");await refreshRuntime();loadUsage()}catch(err){addBubble(`请求失败：${err.message}`,"agent")}};
function addBubble(content,role){$("#messages").append(text("div",content,`bubble ${role}`));$("#messages").scrollTop=$("#messages").scrollHeight}
$("#create-invite").onclick=async()=>{const value=await api(`/api/campaigns/${state.campaign.id}/invites`,{method:"POST",body:JSON.stringify({mode:"request"})});$("#invite-result").textContent=`邀请代码（仅显示一次）：${value.token}`};
async function loadUsage(){if(!state.user)return;const [b,ledger]=await Promise.all([api("/api/usage/balance"),api("/api/usage/ledger")]),total=Number(b.granted),used=Number(b.used),pct=total?Math.min(100,used/total*100):0,root=$("#usage-card");root.replaceChildren(text("p",`${used.toLocaleString()} / ${total.toLocaleString()} tokens 已使用`,"muted"));const meter=text("div","","meter"),fill=text("span","");fill.style.width=`${pct}%`;meter.append(fill);root.append(meter,text("p",`可用 ${Number(b.available).toLocaleString()} tokens`,"eyebrow"));$("#usage-ledger").replaceChildren(text("h3","最近用量"),...ledger.map(x=>text("p",`${new Date(x.occurred_at).toLocaleString()} · ${x.quantity} ${x.unit} · ${x.model||x.provider||"—"}`,"muted")))}
$("#pack-form").onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);try{await api("/api/packs",{method:"POST",body:data});e.target.reset();toast("Pack 已保存到私有库");loadPacks()}catch(err){toast(err.message)}};
async function loadPacks(){state.packs=await api("/api/packs");const root=$("#pack-list");root.replaceChildren();for(const p of state.packs){const card=text("article","","card pack");card.append(text("p",p.kind,"eyebrow"),text("h3",p.title),text("p",`${p.pack_id} · ${p.version}`,"muted"),text("p",`${(p.size_bytes/1024).toFixed(1)} KB · private`,"meta"));root.append(card)}}
setInterval(()=>{if(state.campaign&&!$("#campaign-room").hidden)refreshRuntime().catch(()=>{})},5000);
boot();
