const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={user:null,campaigns:[],campaign:null,conversation:null};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});if(r.status===204)return null;const body=await r.json().catch(()=>({detail:`HTTP ${r.status}`}));if(!r.ok)throw new Error(body.detail||`HTTP ${r.status}`);return body}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function text(tag,value,klass=""){const el=document.createElement(tag);el.textContent=value;if(klass)el.className=klass;return el}
async function boot(){try{state.user=(await api("/api/auth/me")).user;showApp()}catch{$("#auth").hidden=false}}
function showApp(){$("#auth").hidden=true;$("#app").hidden=false;$("#identity").textContent=state.user.display_name;loadCampaigns();loadUsage()}
$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$("#name-row").hidden=b.dataset.mode!=="register";$("#auth-form").dataset.mode=b.dataset.mode});
$("#auth-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),mode=e.target.dataset.mode||"login";try{const body={email:f.get("email"),password:f.get("password")};if(mode==="register")body.display_name=f.get("display_name");state.user=(await api(`/api/auth/${mode}`,{method:"POST",body:JSON.stringify(body)})).user;showApp()}catch(err){$("#auth-error").textContent=err.message}};
$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.reload()};
$$('.nav[data-view]').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.hidden=v.id!==`${b.dataset.view}-view`);if(b.dataset.view==='packs')loadPacks();if(b.dataset.view==='usage')loadUsage()});
async function loadCampaigns(){state.campaigns=await api("/api/campaigns");const list=$("#campaign-list");list.replaceChildren();for(const c of state.campaigns){const card=text("article","","card campaign");card.append(text("p",c.system_id.toUpperCase(),"eyebrow"),text("h3",c.name));const meta=text("div","","meta");meta.append(text("span",c.visibility),text("span",`rev ${c.mcp_revision}`));card.append(meta);card.onclick=()=>openCampaign(c);list.append(card)}}
$("#new-campaign").onclick=()=>$("#campaign-form").hidden=false;$('[data-close]').onclick=()=>$("#campaign-form").hidden=true;
$("#campaign-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api("/api/campaigns",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(Object.fromEntries(f))});e.target.hidden=true;e.target.reset();toast("战役已创建");loadCampaigns()};
async function openCampaign(c){state.campaign=c;$("#campaign-list").hidden=true;$("#new-campaign").hidden=true;$("#campaign-room").hidden=false;$("#room-title").textContent=c.name;const members=await api(`/api/campaigns/${c.id}/members`);const el=$("#members");el.replaceChildren(...members.map(m=>text("p",`${m.display_name} · ${m.role}`)));const convs=await api(`/api/campaigns/${c.id}/agent/conversations`);state.conversation=convs[0]||await api(`/api/campaigns/${c.id}/agent/conversations`,{method:"POST",body:JSON.stringify({title:"战役会话"})})}
$("#back-campaigns").onclick=()=>{$("#campaign-room").hidden=true;$("#campaign-list").hidden=false;$("#new-campaign").hidden=false};
$("#message-form").onsubmit=async e=>{e.preventDefault();const field=e.target.elements.content,content=field.value.trim();if(!content)return;addBubble(content,"user");field.value="";try{const run=await api(`/api/campaigns/${state.campaign.id}/agent/conversations/${state.conversation.id}/messages`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({content})});addBubble(run.assistant_content,"agent");loadUsage()}catch(err){addBubble(`请求失败：${err.message}`,"agent")}};
function addBubble(content,role){$("#messages").append(text("div",content,`bubble ${role}`));$("#messages").scrollTop=$("#messages").scrollHeight}
$("#create-invite").onclick=async()=>{const value=await api(`/api/campaigns/${state.campaign.id}/invites`,{method:"POST",body:JSON.stringify({mode:"request"})});$("#invite-result").textContent=`邀请码（仅显示一次）：${value.token}`};
async function loadUsage(){if(!state.user)return;const b=await api("/api/usage/balance"),total=Number(b.granted),used=Number(b.used),pct=total?Math.min(100,used/total*100):0;const root=$("#usage-card");root.replaceChildren(text("p",`${used.toLocaleString()} / ${total.toLocaleString()} tokens 已使用`,"muted"));const meter=text("div","","meter"),fill=text("span","");fill.style.width=`${pct}%`;meter.append(fill);root.append(meter,text("p",`可用 ${Number(b.available).toLocaleString()} tokens`,"eyebrow"))}
$("#pack-form").onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);try{await api("/api/packs",{method:"POST",body:data});e.target.reset();toast("Pack 已保存到私有库");loadPacks()}catch(err){toast(err.message)}};
async function loadPacks(){const packs=await api("/api/packs"),root=$("#pack-list");root.replaceChildren();for(const p of packs){const card=text("article","","card pack");card.append(text("p",p.kind,"eyebrow"),text("h3",p.title),text("p",`${p.pack_id} · ${p.version}`,"muted"),text("p",`${(p.size_bytes/1024).toFixed(1)} KB · private`,"meta"));root.append(card)}}
boot();
